config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'workshops#index'
  
  resources :account, only: [:index]
  resources :workshops do
    resources :participations
  end
  resources :comments, only: [:create]
  
  get '/account/details/:id', to: 'account#show',  as: 'account'
  get '/account/edit', to: 'account#edit', as: 'edit_account'
  patch '/account/edit', to: 'account#update', as: 'update_account'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :workshop, class_name: "Workshop", optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_and_belongs_to_many :workshops

  validates :email, presence: true, uniqueness: true
end

app/models/workshop.rb
class Workshop < ApplicationRecord
	has_and_belongs_to_many :users
  has_and_belongs_to_many :comments
	
	validates :title, presence: true,
										length: { minimum: 5 }
end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  before_action :set_account, only: [:index, :edit, :update, :destroy]

	def index
		if !user_signed_in?
			return redirect_to new_user_session_path
		end
  end

  def show
    if session[:user_id].nil?
      return redirect_to new_user_session_path
    elsif params[:id] == session[:user_id].to_s
      return redirect_to account_index_url
    end

    @account = User.find(params[:id])
  end

  # GET /account/register
  def register
    @account = User.new
  end

  # GET /account/edit
  def edit
  end

  # POST /account
  def create
    @account = User.new(account_params)

    respond_to do |format|
      if @account.save
        session[:user_id] = @account.id
        format.html { redirect_to root_path }
        format.json { render 'sessions#new', status: :created, location: login_path }
      else
        format.html { render :register }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /account
  def update
    update_params = account_params

    if !params[:user][:picture].nil?
      name = params[:user][:picture].original_filename
      profile_picture_path = File.join('app', 'assets', 'images', 'avatars', name)
  
      update_params[:picture] = File.join('avatars', name)
      File.open(profile_picture_path, 'wb') { |f| f.write(params[:user][:picture].read) }
    end

    respond_to do |format|
      if @account.update(update_params)
        format.html { redirect_to account_index_url, notice: 'User was successfully updated.' }
        format.json { render :index, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_account
			@account = current_user
    end

    def account_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	skip_before_action :verify_authenticity_token, :only => [:create]

	def create 
		if params[:content].nil?
			render :json => { 
				:success => false 
			}
		end
		
		workshop = Workshop.find(params[:workshop_id])
		comment = Comment.new({ 
			:content => params[:content], 
			:user_id => current_user.id,
		})
		
		if comment.save
			workshop.comments.append(comment)

			if workshop.save
				render :json => { 
					:id => comment.id,
					:content => comment.content,
					:created_at => comment.created_at,
					:user_id => comment.user.id,
					:user_avatar => comment.user.picture,
					:user_email => comment.user.email
				}
			else
				render :json => { :result => false }
			end
		else
			render :json => { :result => false }
		end
	end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
	def index
		@workshop = Workshop.find(params[:workshop_id])

		if @workshop.users.exists?(current_user.id)
			@workshop.users.delete(current_user)
		else
			@workshop.users.append(current_user)
		end

		@workshop.save

		redirect_to @workshop
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to root_path }
        format.json { render 'sessions#new', status: :created, location: login_path }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
	before_action :load_workshop, :except => [:index, :new, :create]
  before_action :authorize, :except => [:index, :show]

	def index 
		@workshops = Workshop.all
		WorkshopCleanerJob.perform_later
	end

	def new 
		@workshop = Workshop.new
	end

	def edit
		if @workshop.user_id != current_user.id
			return redirect_to root_url
		end
	end

	def update
		if @workshop.update(workshop_params)
			redirect_to @workshop
		else
			render 'edit'
		end
	end

	def create 
		@workshop = Workshop.new(workshop_params)
		@workshop.user_id = session[:user_id]

		if @workshop.save
			redirect_to @workshop
		else
			render 'new'
		end
	end

	def show 
	end

	def destroy
		if current_user.nil?
			redirect_to login_path
		elsif @workshop.user_id != current_user.id
			return redirect_to root_url
		else
			@workshop.destroy
	
			redirect_to workshops_path
		end
	end

	private
	
	def workshop_params 
		params.require(:workshop).permit(:title, :date)
	end

	def load_workshop
		@workshop = Workshop.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workshop_helper.rb
module WorkshopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyWorkshop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
  <%= javascript_include_tag 'application', 'data-turbolinks-suppress-warning': 'reload', 'data-turbolinks-eval': 'false'  %>
  <% if File.file?("#{Rails.root}/app/assets/javascripts/#{controller_name}.js") %>
    <%= javascript_include_tag controller_name %>
  <% end %>
</html>

app/views/shared/_authorization.html.erb
<% if user_signed_in? %>
	<a href=<%= account_index_path %> class='btn btn-outline-primary account-link'>
		<i class="far fa-user"></i>
	</a>
	<%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-secondary logout-btn' %>
<% else %>
	<%= link_to 'Register', new_user_registration_path, class: "btn btn-primary" %>
	<%= link_to 'Login', new_user_session_path, class: "btn btn-outline-primary" %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar bg-white border-bottom box-shadow p-3 px-md-4 mb-3">
	<div class="container d-flex flex-column flex-md-row align-items-center">
		<div class='d-flex align-items-center'>
			<h5 class="my-0 mr-md-auto font-weight-normal">
				<%= link_to 'Workshop', root_url, class: 'text-dark' %>
			</h5>
			<%= link_to 'Add +', new_workshop_path, class: "btn btn-outline-primary ml-3" %>
		</div>

		<nav class="my-2 my-md-0 md-3">
			<%= render 'shared/authorization' %>
		</nav>
	</div>
</div>

app/views/users/new.html.erb
<div class="row">
	<div class="col-sm-4 offset-sm-4 col-12">
	<h3>Register</h3>
		<%= render 'form', user: @user %>
	</div>
</div>

app/views/workshops/_form.html.erb
<%= form_with model: @workshop, local: true do |form| %>
	<div class="form-group">
		<%= form.label :title %>
		<%= form.text_field :title, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= form.label :date %>
		<%= form.date_field :date, class: 'form-control' %>
	</div>
	<div class="text-right mt-4">
		<%= form.submit 'Create', :class => 'btn btn-outline-success' %>
	</div>
<% end %>

app/views/workshops/_workshop.html.erb
<div class="card card-primary mb-3">
	<div class="card-body">
		<h5 class="card-title">
			<div class="d-flex justify-content-between">
				<%= link_to workshop.title, workshop, class: 'text-decoration-none text-dark' %>
				<% if !local_variables.include?(:no_actions) || (local_variables.include?(:no_actions) && !no_actions) %>
					<% if !current_user.nil? && workshop.user_id === current_user.id && %>
						<div class="actions-container">
							<%= link_to 'Edit', edit_workshop_path(workshop), class: 'btn badge badge-dark' %>
							<%= link_to 'Delete', workshop_path(workshop), 
									method: :delete, 
									data: { confirm: 'Are you sure?' },
									class: 'btn badge badge-danger' %>
						</div>
					<% end%>
				<% end %>
			</div>
		</h5>
		<p class="card-text">
			<% if workshop.date.nil? %>
				<small>No date provided</small>
			<% else %>
				On: <strong><%= workshop.date %></strong>
			<% end %>
		</p>
	</div>
</div>

app/views/workshops/edit.html.erb
<div class="jumbotron mt-5">
	<h2>Edit workshop</h2>
	<%= render 'form' %>
</div>

app/views/workshops/index.html.erb
<h2 class='text-monospace'>Workshops</h2>

<div class="workshops-container mt-3">
	<div class="row">
		<% @workshops.each do |workshop| %>
			<div class="col-6">
				<%= render partial: 'workshops/workshop', locals: { workshop: workshop } %>
			</div>
		<% end %>
	</div>
</div>

app/views/workshops/new.html.erb
<div class="row">
	<div class="col-6 offset-3">
		<div class="jumbotron mt-5">
			<h2>Create a new workshop</h2>
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/workshops/show.html.erb
<div class="workshop-details-page">
	<div class="card" data-workshop-id="<%= @workshop.id %>">
		<div class="card-body">
			<h5 class="card-title">
				<%= @workshop.title %>
			</h5>
			<p class="card-text">
				On: <strong><%= @workshop.date %></strong>
			</p>
			<div class="d-flex justify-content-between">
				<div class="workshop-participants">
					<span class="heading">Participants : </span>
					<% if @workshop.users.empty? %>
						<span class="ml-2 text-muted">No one is intereted yet</span>
					<% else %>
						<div class="participants-container">
							<%  @workshop.users.first(3).each_with_index do |user, index| %>
								<div class="<%= "participant participant-#{index}"%>" >
									<a href="<%= "/account/details/#{user.id}" %>" class='account-avatar-link'>
										<%= image_tag !user.picture.nil? && !user.picture.empty? ? user.picture : "avatar.png", alt: "Profile picture", 
																"data-toggle": "tooltip",  "data-placement": "bottom", "title": user.email %>
									</a>
								</div>
							<% end%>
						</div>
					<% end %>
					
				</div>
				<% if current_user %>			
					<% if @workshop.users.exists?(current_user.id) %>
						<%= link_to "- I lost interest", "/workshops/#{@workshop.id}/participations"  %>
					<% else %>
						<%= link_to "+ I'm interested", "/workshops/#{@workshop.id}/participations"  %>
					<% end %>	
				<% end %>				
			</div>
		</div>
	</div>

	<div class="comments">
		<h3>Comments</h3>
		<hr>
		<% if current_user %>			
			<div class="comment-input-holder">
				<textarea name="comment" class="form-control comment-input" value="" placeholder="<%= !@workshop.comments.empty? ? "Say something.." : "Be the first to comment" %>" ></textarea>
				<div class="btn btn-outline-primary submit-comment-btn">Comment</div>
			</div>
		<% end%>
		<% if !@workshop.comments.empty? %>
			<% @workshop.comments.order(created_at: :desc).each do |comment| %>
				<div class="toast show comment">
					<div class="toast-header">
						<%= image_tag !comment.user.picture.nil? && !comment.user.picture.empty? ? comment.user.picture : "avatar.png", alt: "Profile picture", class: "rounded comment-avatar" %>
						<strong class="mr-auto">
							<%= link_to comment.user.email, account_url(comment.user)  %>
						</strong>
						<small><%= comment.created_at %></small>
					</div>
					<div class="toast-body">
						<%= comment.content %>
					</div>
				</div>
			<% end %>
		<% end %>
	</div>
</div>